apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-shared-data
  labels:
    volume: jupyterhub-shared-data
spec:
  capacity:
    storage: {{.Values.storage.shared.size | quote}}
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: jupyterhub
    name: jupyterhub-shared-data
  nfs:
    # FIXME: use the right IP from service
    server: {{.Values.nfsServer | quote}}
    path: {{.Values.storage.shared.path | quote}} 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyterhub-shared-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.storage.shared.size | quote}} 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-raw-data
  labels:
    volume: jupyterhub-raw-data
spec:
  capacity:
    storage: {{.Values.storage.readOnly.size | quote}}
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: jupyterhub
    name: jupyterhub-raw-data
  nfs:
    # FIXME: use the right IP from service
    server: {{.Values.nfsServer | quote}}
    path: {{.Values.storage.readOnly.path | quote}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyterhub-raw-data
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{.Values.storage.readOnly.size | quote}}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-user-data
  labels:
    volume: jupyterhub-user-data
spec:
  capacity:
    storage: {{.Values.storage.user.size | quote}}
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: jupyterhub
    name: jupyterhub-user-data
  nfs:
    # FIXME: use the right IP from service
    server: {{.Values.nfsServer | quote}}
    path: {{.Values.storage.user.path | quote}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyterhub-user-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.storage.user.path | quote}}


